[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/agenda/index.html"
to = "/seminaires/"

[[redirects]]
from = "/qui-sommes-nous/index.html"
to = "/a-propos/"

[[redirects]]
from = "/seminaires/2022-06-07-seminaires-de-recherche-encommuns-tapas-communs-communautes-et-interet-general/index.html"
to = "/seminaires/2022/seminaires-de-recherche-encommuns-tapas-communs-communautes-et-interet-general/"

[[redirects]]
from = "/projets-de-recherche/2019-tapas-there-are-palteforms-as-alternatives/index.html"
to = "/projets-de-recherche/2019-tapas-there-are-platforms-as-alternatives/"

[[redirects]]
from = "/agenda/archives/index.html"
to = "/seminaires/archives/"

[[redirects]]
from = "/projets/index.html"
to = "/projets-de-recherche/"

[[redirects]]
from = "/seminaires/2015-11-18-seminaires-de-recherche-encommuns-2015-2019/index.html"
to = "/seminaires/2015/seminaires-de-recherche-encommuns-2015-2019/"

[[redirects]]
from = "/projets/2010-propriete-intellectuelle-communs-et-exclusivite/index.html"
to = "/projets-de-recherche/2010-propriete-intellectuelle-communs-et-exclusivite/"

